format = """
([î‚¶](fg:context)\
$nix_shell\
$all\
[î‚´](fg:context))\
$line_break\
[î‚¶](fg:path)\
${custom.watson}\
$directory\
[î‚°](fg:path bg:git)\
$git_branch\
$git_status\
$character
"""

palette = 'xadet'

[palettes.original]
path = '#DA627D'
watson = '#DA627D'
git = '#FCA17D'
context = '#86BBD8'
alert = '#FC6262'

[palettes.xadet]
path = '#bf566d'
watson = '#398039'
git = '#bf7b60'
context = '#5f8599'
alert = '#FC6262'


# Disable the blank line at the start of the prompt
#add_newline = false
[character]
success_symbol = '[î‚°](fg:git)'
error_symbol = '[îƒ‚](bg:git fg:alert)[ ï± ](bg:alert)[îƒ€](fg:alert)'

[directory]
style = "bg:path"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"

[c]
symbol = "î˜ "
style = "bg:context"
format = '[ $symbol ($version) ]($style)'

[cmake]
symbol = "ï‚…"
format = '[ $symbol ($version) ]($style)'
style = "bg:context"

[docker_context]
symbol = "ïŒˆ "
style = "bg:context"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:context"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:context"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:git"
format = '[ $symbol $branch]($style)'

[git_status]
format = '[( $all_status$ahead_behind) ]($style bg:git)'

[golang]
symbol = "î˜§ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = "î· "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[java]
symbol = "î‰– "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[jobs]
style = 'bg:context'
format = '[ $symbol( $number) ]($style)'

[julia]
symbol = "î˜¤ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[nim]
symbol = "ïš¤ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = "î¨"
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[scala]
symbol = "îœ· "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[hg_branch]
symbol = "ï˜ "

[lua]
symbol = "î˜  "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "

[nix_shell]
symbol = "ïŒ“"
format = '[$symbol( $state )]($style)'
style = "bg:context"
impure_msg = ''

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[rlang]
symbol = "ï³’ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[ruby]
symbol = "î‘ "
style = 'bg:context'
format = '[ $symbol( $version) ]($style)'

[spack]
symbol = "ğŸ…¢ "

[cmd_duration]
format = '[îƒ‚](fg:alert bg:context)[ï¨™$duration]($style)[îƒ€](fg:alert bg:context)'
style = "bg:alert"

[custom.watson]
command = 'watson status -p'
when = 'watson status -p | grep -v "No project"'
style = 'bg:watson'
symbol = 'ï¨Ÿ'
format = '[î‚º](bg:path fg:watson)[$symbol($output )]($style)[î‚º](fg:path bg:watson)'
